{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from bottle import route, run, HTTPResponse\n",
    "import requests\n",
    "import csv\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def csvreader(fileaddr = '../data/test.csv'):\n",
    "    csvlist = []\n",
    "    with open(fileaddr, 'r') as f:\n",
    "        reader = csv.reader(f)\n",
    "        for row in reader:\n",
    "            csvlist.append((row[0],row[1]))\n",
    "    \n",
    "    return csvlist"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "@route('/exchangetest')\n",
    "def hello2():\n",
    "    message = 'そマ? テンサゲ～'\n",
    "    exchange_tapple = csvreader()\n",
    "    for before, after in exchange_tapple:\n",
    "        message = message.replace(before, after)\n",
    "    \n",
    "    print(message)\n",
    "    body = {\"status\": \"OK\", \"message\": message}\n",
    "    r = HTTPResponse(status=200, body=body)\n",
    "    r.set_header(\"Content-Type\", \"application/json\")\n",
    "    return r"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Bottle v0.12.13 server starting up (using WSGIRefServer())...\n",
      "Listening on http://0.0.0.0:8080/\n",
      "Hit Ctrl-C to quit.\n",
      "\n",
      "183.74.193.16 - - [21/Oct/2017 05:20:11] \"GET /exchangetest HTTP/1.1\" 200 117\n",
      "183.74.193.16 - - [21/Oct/2017 05:22:00] \"GET /exchangetest HTTP/1.1\" 200 117\n",
      "----------------------------------------\n",
      "Exception happened during processing of request from ('183.74.193.16', 49800)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 696, in __init__\n",
      "    self.handle()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/simple_server.py\", line 118, in handle\n",
      "    self.raw_requestline = self.rfile.readline(65537)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socket.py\", line 586, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception happened during processing of request from ('183.74.193.16', 49803)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 696, in __init__\n",
      "    self.handle()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/simple_server.py\", line 118, in handle\n",
      "    self.raw_requestline = self.rfile.readline(65537)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socket.py\", line 586, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n",
      "----------------------------------------\n",
      "/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/bottle.py:3468: DeprecationWarning: Flags not at the start of the expression \"((?m)[urbURB]?(?:''(\" (truncated)\n",
      "  patterns = [re.compile(p%pattern_vars) for p in patterns]\n",
      "/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/bottle.py:3468: DeprecationWarning: Flags not at the start of the expression '\\\\{\\\\{((?:((?m)[urbURB' (truncated)\n",
      "  patterns = [re.compile(p%pattern_vars) for p in patterns]\n",
      "183.74.193.16 - - [21/Oct/2017 05:22:28] \"GET /favicon.ico HTTP/1.1\" 404 746\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 138, in run\n",
      "    self.finish_response()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 180, in finish_response\n",
      "    self.write(data)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 274, in write\n",
      "    self.send_headers()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 332, in send_headers\n",
      "    self.send_preamble()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 252, in send_preamble\n",
      "    self._write(('HTTP/%s %s\\r\\n' % (self.http_version,self.status)).encode('iso-8859-1'))\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 453, in _write\n",
      "    result = self.stdout.write(data)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 775, in write\n",
      "    self._sock.sendall(b)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n",
      "183.74.193.16 - - [21/Oct/2017 05:22:28] \"GET /favicon.ico HTTP/1.1\" 500 59\n",
      "----------------------------------------\n",
      "Exception happened during processing of request from ('183.74.193.16', 49802)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 138, in run\n",
      "    self.finish_response()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 180, in finish_response\n",
      "    self.write(data)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 274, in write\n",
      "    self.send_headers()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 332, in send_headers\n",
      "    self.send_preamble()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 252, in send_preamble\n",
      "    self._write(('HTTP/%s %s\\r\\n' % (self.http_version,self.status)).encode('iso-8859-1'))\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 453, in _write\n",
      "    result = self.stdout.write(data)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 775, in write\n",
      "    self._sock.sendall(b)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 141, in run\n",
      "    self.handle_error()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 368, in handle_error\n",
      "    self.finish_response()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 180, in finish_response\n",
      "    self.write(data)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 274, in write\n",
      "    self.send_headers()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 331, in send_headers\n",
      "    if not self.origin_server or self.client_is_modern():\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 344, in client_is_modern\n",
      "    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'\n",
      "TypeError: 'NoneType' object is not subscriptable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/socketserver.py\", line 696, in __init__\n",
      "    self.handle()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/simple_server.py\", line 133, in handle\n",
      "    handler.run(self.server.get_app())\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/handlers.py\", line 144, in run\n",
      "    self.close()\n",
      "  File \"/home/ubuntu/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/wsgiref/simple_server.py\", line 35, in close\n",
      "    self.status.split(' ',1)[0], self.bytes_sent\n",
      "AttributeError: 'NoneType' object has no attribute 'split'\n",
      "----------------------------------------\n",
      "183.74.193.16 - - [21/Oct/2017 05:22:54] \"GET /hello HTTP/1.1\" 404 734\n"
     ]
    }
   ],
   "source": [
    "run(host='0.0.0.0', port=8080, debug=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
